console.log(JSON.stringify([
 {id:"bmi",photo:"bmi_brand",photoAlt:"BMI vacuum furnace installation",name:"BMI",full:"Fours Industriels B.M.I.",country:"France",site:"https://www.bmi-fours.com",
  intro:"Vacuum furnaces for hardening, brazing, tempering and thermochemical treatment, designed and built in France since the early 1980s.",
  cats:[
   {id:"gas-quenching",photo:"bmi_gas",photoAlt:"BMI horizontal vacuum gas quenching furnace",name:"Gas quenching furnaces",sub:"Hardening, brazing and laboratory furnaces",
    desc:"Vacuum furnaces that heat parts without oxidation and then cool them with high-pressure gas. BMI's patented rotating gas-flow system gives uniform quenching even on dense or complex loads.",
    url:"https://www.bmi-fours.com/products/#gas-cooling",
    machines:[
     {id:"b8t",photo:"b8t",photoAlt:"BMI horizontal vacuum gas quenching furnace",name:"B8_T vacuum gas quenching furnace",tag:"Horizontal",short:"Front-loading furnace for high-throughput production.",
      desc:"The B8_T is BMI's horizontal-loading vacuum gas quenching furnace, built for high-throughput production. Parts are heated under vacuum and quenched with gas at 5 to 12 bar, with BMI's patented rotating volute keeping gas flow even through the whole load. It is fully automated for precise, repeatable cycles with clean surfaces and minimal distortion.",
      features:["Horizontal front loading","Gas quenching at 5 to 12 bar abs","Patented rotating volute for uniform cooling","GRAPHTIL® man-machine interface","Graphite, molybdenum or fibre hot zones"],
      specs:[["Working zone","450 × 450 × 600 mm to 900 × 900 × 1200 mm"],["Load capacity","200 to 3000 kg"],["Maximum temperature","1250 °C, 1350 °C or 1500 °C"],["Vacuum level","10⁻² mbar, 10⁻⁵ mbar or 10⁻⁶ mbar"],["Quench pressure","5 to 12 bar abs"],["Hot zone","Graphite, molybdenum or fibre/wool combinations"],["Control","GRAPHTIL® man-machine interface"]],
      process:["Hardening and gas quenching","Hyperquenching","Bright annealing","Solution annealing of stainless steel","Ageing","Stress relieving","Brazing","Sintering","Special alloy degassing","Steel tempering","ALLCARB® low-pressure carburizing"],
      url:"https://www.bmi-fours.com/products/vacuum-hardening-furnace/",k:"vacuum hardening quench tool steel dies",i:["tools","auto","aero"]},
     {id:"vse8t",photo:"vse8t",photoAlt:"BMI vertical vacuum furnace",name:"VSE8_T vacuum gas quenching furnace",tag:"Vertical",short:"Bottom-loading furnace for tall or delicate parts.",
      desc:"The VSE8_T is BMI's bottom-loading vertical vacuum gas quenching furnace. Loading from below suits long, tall or delicate components that must be treated standing or hanging to limit distortion. It shares the B8_T's high-pressure gas quenching and patented rotating volute.",
      features:["Vertical bottom loading","Gas quenching at 5 to 12 bar abs","Patented rotating volute for uniform cooling","GRAPHTIL® man-machine interface","Graphite, molybdenum or fibre hot zones"],
      specs:[["Working zone","Ø 600 × h 600 mm to Ø 1800 × h 1800 mm"],["Load capacity","200 to 3000 kg"],["Maximum temperature","1250 °C, 1350 °C or 1500 °C"],["Vacuum level","10⁻² mbar, 10⁻⁵ mbar or 10⁻⁶ mbar"],["Quench pressure","5 to 12 bar abs"],["Control","GRAPHTIL® man-machine interface"]],
      process:["Hardening and gas quenching","Hyperquenching","Bright annealing","Ageing","Stress relieving","Brazing","Sintering","Steel tempering"],
      url:"https://www.bmi-fours.com/products/vacuum-hardening-furnace/",k:"vacuum hardening long parts shafts",i:["aero","auto"]},
     {id:"brazing",photo:"bmi_brazing",photoAlt:"BMI vacuum furnace with loading truck",name:"Vacuum brazing furnace",short:"Oxide-free brazing of assemblies.",
      desc:"Vacuum furnace for brazing assemblies in a clean, oxide-free atmosphere, used widely in aerospace and for high-value components where joint quality matters.",
      features:["Oxide-free brazing under vacuum","Controlled heating and cooling","Suited to nickel and other brazing alloys"],
      process:["Vacuum brazing","Degassing"],url:"https://www.bmi-fours.com/products/vacuum-brazing-furnace/",k:"brazing assemblies",i:["aero","medical"]},
     {id:"lab",name:"Compact laboratory furnace",short:"Small vacuum furnace for R&D and process development.",
      desc:"A compact vacuum furnace for laboratories, universities and R&D departments, for developing and validating heat-treatment cycles before scaling up to production.",
      features:["Compact footprint","Vacuum heat treatment at laboratory scale","Process development and testing"],
      process:["Hardening","Brazing","Annealing","Process trials"],url:"https://www.bmi-fours.com/products/laboratory-furnace/",k:"lab r&d laboratory",i:[]}
    ]},
   {id:"oil-quenching",photo:"bmi_oil",photoAlt:"BMI vacuum furnace installation",name:"Oil quenching furnaces",sub:"Horizontal and vertical",
    desc:"Vacuum furnaces with an integrated oil quench for steels that need a faster quench than gas can provide.",
    url:"https://www.bmi-fours.com/products/#oil-quenching",
    machines:[
     {id:"oil-horizontal",name:"Vacuum oil quenching furnace, horizontal",tag:"Horizontal",short:"Vacuum heating with an integrated oil quench.",
      desc:"Horizontal vacuum furnace with an integrated oil quench tank, for steels and part sections that need a more severe quench than gas.",
      features:["Vacuum heating without oxidation","Integrated oil quench","Horizontal loading"],process:["Hardening","Oil quenching","Carburizing followed by oil quench"],
      url:"https://www.bmi-fours.com/products/oil-quenching-furnace/",k:"hardening oil",i:["auto"]},
     {id:"oil-vertical",name:"Vacuum oil quenching furnace, vertical",tag:"Vertical",short:"For long parts quenched hanging.",
      desc:"Vertical vacuum oil quenching furnace for long parts that must be quenched hanging to limit distortion.",
      features:["Vertical loading","Integrated oil quench","Reduced distortion on long parts"],process:["Hardening","Oil quenching"],
      url:"https://www.bmi-fours.com/products/vertical-oil-quenching-furnace/",k:"hardening long parts oil",i:["auto"]}
    ]},
   {id:"low-temperature",photo:"bmi_low",photoAlt:"BMI vacuum furnaces on the shop floor",name:"Low-temperature furnaces",sub:"Tempering and aluminium brazing",
    desc:"Vacuum furnaces for lower-temperature processes such as tempering after hardening and brazing aluminium assemblies.",
    url:"https://www.bmi-fours.com/products/#low-temperature",
    machines:[
     {id:"tempering",name:"Vacuum tempering furnace",short:"Tempering after hardening.",
      desc:"Vacuum tempering furnace for tempering hardened parts with clean surfaces and uniform temperature through the load.",
      features:["Vacuum or protective atmosphere","Uniform load temperature","Clean, bright surfaces"],process:["Tempering","Stress relieving","Ageing"],
      url:"https://www.bmi-fours.com/products/tempering-furnace/",k:"tempering",i:["tools","auto"]},
     {id:"alu-brazing",name:"Aluminium brazing vacuum furnace",short:"For heat exchangers and aluminium assemblies.",
      desc:"Vacuum furnace for fluxless brazing of aluminium assemblies such as heat exchangers.",
      features:["Fluxless aluminium brazing","Tight temperature uniformity"],process:["Aluminium vacuum brazing"],
      url:"https://www.bmi-fours.com/products/aluminum-brazing-furnace/",k:"heat exchanger brazing aluminium",i:["auto","aero"]}
    ]},
   {id:"thermochemical",photo:"bmi_thermo",photoAlt:"BMI vacuum furnace with pumping system",name:"Thermochemical treatment furnaces",sub:"Carburizing, nitriding and sub-zero",
    desc:"Furnaces and BMI's own processes for changing the surface chemistry of steel parts, such as carburizing and nitriding, plus sub-zero treatment.",
    url:"https://www.bmi-fours.com/products/#process",
    machines:[
     {id:"allcarb",name:"ALLCARB® low-pressure carburizing",short:"Case hardening for gears and transmission parts.",
      desc:"BMI's ALLCARB® low-pressure carburizing process, run in its vacuum furnaces, case-hardens steel parts such as gears and transmission components without intergranular oxidation.",
      features:["Low-pressure (vacuum) carburizing","No intergranular oxidation","Can be combined with high-pressure gas quenching"],process:["Low-pressure carburizing","Carbonitriding"],
      url:"https://www.bmi-fours.com/products/low-pressure-carburizing/",k:"lpc carburizing gears case hardening",i:["auto"]},
     {id:"allnit",name:"ALLNIT® low-pressure nitriding",short:"Nitriding for wear and fatigue resistance.",
      desc:"BMI's ALLNIT® low-pressure nitriding process for improving wear and fatigue resistance of steel parts and tools.",
      features:["Low-pressure nitriding","Controlled nitrided layer"],process:["Nitriding","Nitrocarburizing"],
      url:"https://www.bmi-fours.com/products/low-pressure-nitriding/",k:"nitriding",i:["auto","tools"]},
     {id:"plasma-nitriding",name:"Plasma nitriding furnace",short:"Ion nitriding for tools, dies and engineering parts.",
      desc:"Plasma (ion) nitriding furnace for tools, dies and engineering components.",
      features:["Plasma-assisted nitriding","Selective treatment possible"],process:["Plasma nitriding"],
      url:"https://www.bmi-fours.com/products/plasma-nitriding-furnace/",k:"ion nitriding dies moulds plasma",i:["tools","auto"]},
     {id:"cool-plus",name:"COOL PLUS sub-zero treatment furnace",short:"Cryogenic treatment of hardened steels.",
      desc:"The COOL PLUS vacuum furnace performs sub-zero cryogenic treatment, stabilising hardened steels by converting retained austenite.",
      features:["Sub-zero cryogenic treatment","Dimensional stabilisation"],process:["Sub-zero treatment","Cryogenic treatment"],
      url:"https://www.bmi-fours.com/products/sub-zero/",k:"cryogenic deep cryo sub-zero",i:["tools","aero"]}
    ]}
  ]},
 {id:"novatec",photo:"nov_main",photoAlt:"Novatec PLURITANK multi-chamber ultrasonic cleaning line",name:"Novatec",full:"Novatec S.r.l., San Martino di Lupari (Padova)",country:"Italy",site:"https://novatec.it/en",
  intro:"Industrial ultrasonic cleaning systems engineered, built and tested in Italy since 1993.",
  cats:[
   {id:"pluritank",photo:"nov_main",photoAlt:"Novatec PLURITANK multi-chamber cleaning line",name:"PLURITANK multi-chamber lines",sub:"Modular lines up to 12 stages",
    desc:"Multi-stage ultrasonic cleaning lines where parts move through cleaning, rinsing and drying stations in sequence. Built to the customer's parts, cleanliness target and throughput.",
    url:"https://novatec.it/en/multi-chamber-ultrasonic-cleaning",
    machines:[
     {id:"pluritank-line",photo:"nov_main",photoAlt:"Novatec PLURITANK multi-chamber ultrasonic cleaning line",gallery:[["nm_pluri","PLURITANK automatic ultrasonic cleaning system"],["nm_brand","PLURITANK line in a cleanroom"],["nov_brand","Inside a PLURITANK line"]],name:"PLURITANK ultrasonic cleaning line",short:"Serial and large-format parts, up to 12 stages.",
      desc:"PLURITANK is Novatec's modular multi-chamber ultrasonic cleaning line. Stages for ultrasonic cleaning, rinsing and drying are combined to suit the part, the contamination and the required cleanliness, with up to 12 stages per line.",
      features:["Modular, up to 12 stages, with room for future hardware and software upgrades","Multi-frequency ultrasonic groups","User-friendly HMI with multiple programs","Data exchange and traceability","AISI 304/316 stainless construction","Factory acceptance test with your sample parts"],
      process:["Degreasing","Ultrasonic cleaning","Rinsing","Drying"],url:"https://novatec.it/en/multi-chamber-ultrasonic-cleaning",k:"ultrasonic cleaning washing rinsing drying",i:["auto","medical","optics","watch","semi","tools"]},
     {id:"pre-pvd",name:"PLURITANK pre-treatment line for PVD coating",short:"Surface preparation before PVD, CVD and DLC.",
      desc:"A PLURITANK line configured to prepare tools and components for coating. Ultrasonic cleaning followed by rinsing and drying removes residues so the coating bonds reliably, batch after batch.",
      features:["Reproducible pre-coating cleanliness","Rinsing and drying cycles","Matched to coating plant capacity"],
      process:["Pre-PVD cleaning","Pre-CVD cleaning","Pre-DLC cleaning"],url:"https://novatec.it/en/multi-chamber-ultrasonic-cleaning",k:"pvd pre-treatment coating cleaning",i:["tools"]},
     {id:"cleanroom",photo:"nm_clean",photoAlt:"Novatec cleaning line for cleanroom use",name:"Cleanroom cleaning line",short:"Low-particle cleaning for semiconductor and medical.",
      desc:"Precision cleaning for semiconductor hardware, vacuum-chamber parts and medical devices. Cleanroom class 7 design is available, with ultrapure water rinsing and documentation for validated processes.",
      features:["Cleanroom class 7 design available","Ultrapure water rinsing","IQ/OQ/PQ documentation for medical"],
      process:["Precision cleaning","Ultrapure rinsing","Drying"],url:"https://novatec.it/en/products",k:"cleanroom semiconductor medical implants",i:["semi","medical"]}
    ]},
   {id:"2crd",photo:"crd_green",photoAlt:"Novatec 2CRD single-chamber precision cleaning system",name:"2CRD single-chamber systems",sub:"Vacuum cleaning with rotating basket, 8 sizes",
    desc:"Compact single-chamber systems that clean and vacuum-dry in one chamber, with a rotating basket to reach blind holes and complex geometry.",
    url:"https://novatec.it/en/2crd-vacuum-cleaning",
    machines:[
     {id:"2crd-system",photo:"crd_green",photoAlt:"Novatec 2CRD single-chamber precision cleaning system",gallery:[["nm_2crd","Novatec 2CRD400 one-chamber vacuum cleaning system"],["nm_2crd_b","2CRD one-chamber system"],["nov_2crd","Single-chamber precision cleaning system"]],name:"2CRD vacuum precision cleaning system",short:"Cleaning and vacuum drying in one chamber.",
      desc:"The 2CRD is Novatec's aqueous one-chamber vacuum cleaning system. It combines ultrasonic frequencies with vacuum processes and flexible cleaning, rinsing and drying steps in one compact chamber with a rotating basket. It is especially suited to blind and tapped holes, porous-coated surfaces and complex parts carrying polishing pastes and oils, including medical implants between production steps. Models include the 2CRD400, and the range comes in 8 sizes.",
      features:["Single chamber: clean, rinse and vacuum dry","Ultrasonic cleaning combined with vacuum processes","Cleans blind and tapped holes and porous-coated surfaces","Rotating basket","Compact footprint, 8 sizes"],process:["Ultrasonic cleaning","Rinsing","Vacuum drying"],
      url:"https://novatec.it/en/2crd-vacuum-cleaning",k:"precision cleaning vacuum drying blind holes 2crd400 implants polishing paste",i:["medical","semi","watch","auto"]}
    ]},
   {id:"medical-implants",photo:"nm_implants",photoAlt:"Orthopaedic implants cleaned on Novatec systems",name:"Medical implant processing",sub:"In-process cleaning, final cleaning, passivation and FPI",
    desc:"Complete cleaning and treatment systems for orthopaedic and medical implant makers, from cleaning between machining and polishing steps to final cleaning and passivation into the cleanroom. Every system is customised to the customer's user requirement specification (URS) and can be supplied as a single machine or a combined, fully automated line.",
    url:"https://novatec.it/en/products",
    machines:[
     {id:"ipc",photo:"nm_ipc",photoAlt:"Novatec PLURITANK in-line cleaning system for implants",gallery:[["nm_2crd","2CRD400 one-chamber vacuum system"],["nm_basket","Implants in a cleaning basket"]],name:"IPC in-process cleaning",tag:"One-chamber or in-line",short:"Cleaning implants between production steps.",
      desc:"In-process cleaning (IPC) removes oils, chips, particles and polishing pastes from implants between grinding, blasting and polishing steps. Novatec offers it as a one-chamber 2CRD vacuum system for blind holes, porous coatings and complex shapes, or as an in-line PLURITANK system for higher volumes and a wider mix of parts.",
      features:["One-chamber 2CRD vacuum systems or in-line PLURITANK systems","Ultrasonic cleaning combined with vacuum processes","Handles blind and tapped holes and porous-coated surfaces","Multi-frequency ultrasonic groups","Data exchange and traceability","Modular for future hardware and software upgrades"],
      process:["Removing polishing pastes and oils","Cleaning after grinding and blasting","Cleaning between machining steps"],url:"https://novatec.it/en/products",k:"ipc in-process cleaning implants orthopaedic polishing paste 2crd pluritank",i:["medical"]},
     {id:"fcps",photo:"nm_fcps",photoAlt:"Novatec final cleaning line with unload air lock to cleanroom",gallery:[["nm_brand","Final cleaning line in a cleanroom"],["nm_fcps_b","Transfer through the line"],["nm_fcps_c","Unloading into the cleanroom"],["nm_fcps_d","Implant basket leaving the line"]],name:"FCS / FCPS final cleaning and passivation",tag:"Cleanroom unload",short:"Final cleaning, with optional passivation, into the cleanroom.",
      desc:"After in-process cleaning, implants need a final clean to remove dust and handling residues before sterilisation and packaging. The FCS (final cleaning system) or FCPS (combined final cleaning and passivation system) is an automatic PLURITANK line that unloads through an air lock straight into the cleanroom, leaving parts free of contaminants, stains and organic or biological residues.",
      features:["Final cleaning, or combined final cleaning and passivation","Unload air lock directly into the cleanroom","Support with final qualification (IQ, OQ)","Material and calibration certificates","Multi-frequency ultrasonic groups","Data exchange and traceability"],
      process:["Final cleaning before sterilisation","Passivation","Cleanroom transfer"],url:"https://novatec.it/en/products",k:"fcs fcps final cleaning passivation cleanroom air lock implants sterilisation",i:["medical"]},
     {id:"fpi",photo:"nm_fpi",photoAlt:"3D layout of a Novatec PLURITANK FPI line",gallery:[["nm_fpi_b","Parts under UV inspection"],["nm_fpi_c","FPI line installation"],["nm_fpi_d","Automated FPI line"]],name:"FPI fluorescent penetrant inspection line",tag:"PLURITANK",short:"Automated cleaning and crack detection.",
      desc:"An automatic PLURITANK line that combines surface cleaning, preparation and fluorescent penetrant inspection in one fully automated process. It is used to validate medical implants during manufacturing by revealing flaws, cracks and signs of fatigue, with automated part transfer for high throughput and a stable process.",
      features:["Cleaning, preparation and FPI in one automated line","Reveals flaws, cracks and fatigue signs","Automated part transfer for high throughput","Custom-designed to the customer's specification"],
      process:["Fluorescent penetrant inspection","Pre-inspection cleaning","Part validation"],url:"https://novatec.it/en/products",k:"fpi fluorescent penetrant inspection ndt cracks implants aerospace",i:["medical","aero"]},
     {id:"combined",photo:"nm_urs",photoAlt:"Layout of a combined Novatec implant cleaning project",gallery:[["nm_urs_b","Implants in custom baskets"]],name:"Combined turnkey implant lines (URS)",tag:"All-in project",short:"Complete, automated implant cleaning plant.",
      desc:"For larger projects Novatec designs the whole cleaning area to the customer's URS, linking the individual systems with conveyors and full automatic management. A typical line includes automatic basket loading with scanners and RFID, IPC one-chamber vacuum systems, quality verification stations, a combined final cleaning and passivation system, spray cleaning with an unload air lock, and a basket return conveyor, all with data exchange for traceability.",
      features:["Automatic basket loading station with scanners and RFID","IPC one-chamber vacuum systems","QVS quality verification stations","FCPS final cleaning and passivation with air lock to cleanroom","PFC spray cleaning system with unload air lock","BRC basket return air-lock conveyor","Full automatic management and data exchange for traceability"],
      process:["In-process cleaning","Final cleaning and passivation","Quality verification","Cleanroom transfer"],url:"https://novatec.it/en/products",k:"urs turnkey combined implants rfid qvs pfc brc cleanroom",i:["medical"]}
    ]},
   {id:"components",photo:"nov_gen",photoAlt:"Novatec ultrasonic generators",name:"Ultrasonic components",sub:"Generators, transducers and PLT 60V",
    desc:"The ultrasonic building blocks Novatec uses in its own systems, also supplied for building or upgrading tanks.",
    url:"https://novatec.it/en/ultrasonic-components",
    machines:[
     {id:"generators",photo:"nov_gen",photoAlt:"Novatec ultrasonic generators",gallery:[["nov_trans","Immersible ultrasonic transducers"]],name:"Ultrasonic generators and transducers",short:"For building or upgrading cleaning tanks.",
      desc:"Ultrasonic generators and transducers for building new cleaning tanks or upgrading existing ones.",
      features:["Generators and transducers","For new tanks or retrofits"],process:["Ultrasonic cleaning"],url:"https://novatec.it/en/ultrasonic-components",k:"generator transducer",i:[]},
     {id:"plt60v",name:"PLT 60V pressure-cycle unit",short:"Pressure-change cleaning for internal channels.",
      desc:"The PLT 60V uses pressure cycling to clean internal channels and cavities that ultrasound alone struggles to reach.",
      features:["Pressure-cycle cleaning","Reaches internal channels and cavities"],process:["Pressure-change cleaning"],url:"https://novatec.it/en/ultrasonic-components",k:"pressure cleaning channels",i:["auto","medical"]}
    ]}
  ]},
 {id:"huasheng",photo:"lineup",photoAlt:"Huasheng coating machines: HA802, MA1500, HiPIMS, TC802 and MC1000",name:"Huasheng",full:"Guangdong Huasheng Nanotechnology Co., Ltd.",country:"China",site:"https://www.hscoat.com",
  intro:"PVD, DLC, diamond, optical and CVD coating equipment, plus complete turnkey coating plants.",
  cats:[
   {id:"pvd",photo:"hs_pvd",photoAlt:"Huasheng G4PRO PVD coating machine",name:"PVD coating equipment",sub:"Arc, HiPIMS, hybrid and decorative",
    desc:"Physical vapour deposition systems for hard, wear-resistant coatings on cutting tools, moulds and components, and for decorative colour finishes.",
    url:"https://www.hscoat.com/pvd-coating-equipment/",
    machines:[
     {id:"md800",name:"MD800 arc coating machine",tag:"Arc coating",photo:"ma800",photoAlt:"Huasheng MA800Plus arc coating machine",gallery:[["hs_md","Huasheng MD series coating machine"]],short:"High-rate arc coater for tool coating production.",
      desc:"The MD800 is the arc coating machine at the heart of Huasheng's turnkey tool-coating plant. Low-voltage, high-current arc discharge evaporates and ionises the target material, which is deposited on the tools under an electric field, giving a high deposition rate and strong coating adhesion.",
      features:["Arc coating with high deposition rate","High ionisation rate and good coverage on complex shapes","Very high impact resistance of coatings","Fully automatic operation"],
      specs:[["Technology","Arc coating"],["Capacity","12,000 pcs per batch (APMT1135 inserts)"],["Operation","Fully automatic"]],
      process:["TiAlN, AlCrN and similar hard coatings","Inserts, drills and end mills"],url:"https://www.hscoat.com/aip-coating-equipment/",k:"pvd arc aip tialn inserts drills end mills md800 turnkey",i:["tools"]},
     {id:"aip",photo:"hs_pvd",photoAlt:"Huasheng G4PRO arc coating machine",name:"Arc coating equipment",tag:"Arc coating",short:"Hard nitride coatings for cutting tools.",
      desc:"Arc coating systems for hard nitride coatings such as TiAlN and AlCrN on inserts, drills, end mills and forming tools.",
      features:["High deposition rate","Strong adhesion","Multilayer and nano-layer coatings"],process:["Cutting tool coating","Mould and die coating"],
      url:"https://www.hscoat.com/aip-coating-equipment/",k:"pvd tialn alcrn inserts drills end mills cutting tools arc",i:["tools"]},
     {id:"hipims",photo:"hs_hipims",photoAlt:"Huasheng HiPIMS coating machine",name:"HiPIMS coating equipment",short:"Dense, smooth, droplet-free coatings.",
      desc:"High-power impulse magnetron sputtering systems that produce dense, smooth coatings without the droplets typical of arc processes.",
      features:["High-density plasma","Smooth, droplet-free surfaces"],process:["Precision tool coating","Component coating"],
      url:"https://www.hscoat.com/hipims-coating-equipment/",k:"pvd sputtering smooth hipims",i:["tools","medical","auto"]},
     {id:"hybrid",name:"Hybrid coating equipment",short:"Arc and sputtering in one chamber.",
      desc:"Hybrid systems that combine arc and sputtering sources in one chamber for multilayer coating designs.",
      features:["Multiple processes in one chamber","Flexible multilayer designs"],process:["Multilayer tool and component coatings"],
      url:"https://www.hscoat.com/hybrid-coating-equipment/",k:"pvd arc sputtering multilayer hybrid",i:["tools","auto"]},
     {id:"decorative",name:"Decorative coating equipment",short:"Colour PVD finishes.",
      desc:"PVD systems for durable colour finishes on hardware, sanitaryware, watches and consumer products.",
      features:["Wide colour range","Durable, wear-resistant finishes"],process:["Decorative PVD"],
      url:"https://www.hscoat.com/decorative-coating-equipment/",k:"colour gold black decorative sanitary",i:["watch"]}
    ]},
   {id:"dlc",photo:"hs_dlc",photoAlt:"Huasheng DLC coating system",name:"DLC coating equipment",sub:"PECVD DLC and ta-C",
    desc:"Diamond-like carbon coating systems for low friction and high hardness.",url:"https://www.hscoat.com/dlc-coating-equipment/",
    machines:[
     {id:"pecvd-dlc",photo:"hs_dlc",photoAlt:"Huasheng DLC coating system",name:"PECVD DLC coating equipment",short:"Low-friction coatings for components.",
      desc:"Plasma-enhanced CVD systems for low-friction DLC coatings on automotive and engineering components such as piston pins.",
      features:["Low friction","High hardness and wear resistance"],process:["Automotive component coating","Engineering component coating"],
      url:"https://www.hscoat.com/pecvd-dlc-coating-equipment/",k:"dlc low friction piston pin pecvd",i:["auto","medical"]},
     {id:"tac",photo:"hs_tc802",photoAlt:"Huasheng TC802 coating machine",name:"ta-C coating equipment",short:"Hydrogen-free carbon coatings.",
      desc:"Systems for hydrogen-free tetrahedral amorphous carbon (ta-C) coatings, used for machining non-ferrous materials and for high-wear parts.",
      features:["Hydrogen-free carbon","Very high hardness"],process:["Tools for aluminium and non-ferrous machining","High-wear components"],
      url:"https://www.hscoat.com/ta-c-coating-equipment/",k:"tac hydrogen-free carbon aluminium machining",i:["tools","auto"]}
    ]},
   {id:"diamond",photo:"hs_diamond",photoAlt:"Huasheng coating system",name:"Diamond coating equipment",sub:"HFCVD",desc:"Hot-filament CVD systems that grow diamond films on carbide tools.",url:"https://www.hscoat.com/diamond-coating-equipment/",
    machines:[
     {id:"hfcvd",name:"HFCVD diamond coating equipment",short:"Diamond films on carbide tools.",
      desc:"Hot-filament CVD systems that deposit diamond on carbide tools for machining graphite, composites and aluminium-silicon alloys.",
      features:["Very high hardness","Long tool life on abrasive materials"],process:["Carbide tool coating"],
      url:"https://www.hscoat.com/hfcvd-diamond-coating-equipment/",k:"diamond carbide graphite composites hfcvd",i:["tools","aero"]}
    ]},
   {id:"optical",photo:"hs_mc1000",photoAlt:"Huasheng MC1000 coating machine",name:"Optical coating equipment",sub:"Evaporation and magnetron sputtering",desc:"Systems for optical thin films on lenses and optical components.",url:"https://www.hscoat.com/optical-coating-equipment/",
    machines:[
     {id:"evaporation",name:"Evaporation optical coating equipment",short:"Anti-reflection and filter coatings.",
      desc:"Evaporation systems for anti-reflection and filter coatings on lenses and optics.",features:["Anti-reflection coatings","Filter coatings"],process:["Lens coating"],
      url:"https://www.hscoat.com/evaporation-optical-coating-equipment/",k:"anti-reflection lenses evaporation",i:["optics"]},
     {id:"sputter-optical",name:"Magnetron sputtering optical coating equipment",short:"Precise multilayer optical films.",
      desc:"Magnetron sputtering systems for precise multilayer optical films.",features:["Precise layer control","Multilayer films"],process:["Optical filters","Precision optics"],
      url:"https://www.hscoat.com/magnetron-sputtering-optical-coating-equipment/",k:"optical films sputtering",i:["optics","semi"]}
    ]},
   {id:"cvd",photo:"hs_ma1500",photoAlt:"Huasheng MA1500 coating machine",name:"CVD coating equipment",sub:"CVD and CVA aluminizing",desc:"Chemical vapour deposition systems for thick wear-resistant and high-temperature coatings.",url:"https://www.hscoat.com/cvd-coating-equipment/",
    machines:[
     {id:"cvd-systems",name:"CVD coating systems",short:"Thick wear-resistant coatings.",
      desc:"CVD systems for thick wear-resistant coatings, typically on turning inserts.",features:["Thick, wear-resistant layers"],process:["Turning insert coating"],
      url:"https://www.hscoat.com/cvd-coating-systems/",k:"cvd inserts turning",i:["tools"]},
     {id:"cva",name:"CVA aluminizing systems",short:"Aluminide coatings for high-temperature parts.",
      desc:"Chemical vapour aluminizing systems for aluminide coatings that protect parts against high-temperature oxidation.",features:["High-temperature oxidation resistance"],process:["Turbine and hot-section parts"],
      url:"https://www.hscoat.com/cva-aluminizing-systems/",k:"aluminide turbine oxidation cva",i:["aero"]}
    ]},
   {id:"turnkey",photo:"turnkey",photoAlt:"Layout of the Huasheng turnkey coating plant",name:"Turnkey coating solutions",sub:"Complete MD800 tool-coating plant",desc:"A complete tool-coating centre from Huasheng: cleaning, coating, maintenance, utilities and quality control, laid out and commissioned as one plant.",url:"https://www.hscoat.com/turnkey-solution/",
    machines:[
     {id:"md800-turnkey",name:"MD800 turnkey coating centre",photo:"turnkey",photoAlt:"Layout of the Huasheng turnkey coating plant: cleaning, coating, chiller, sandblasting and quality control",gallery:[["cleanline","Fully automatic ultrasonic cleaning line"],["ma800","MA800Plus arc coating machine"]],short:"Complete plant for in-house tool coating.",
      desc:"Huasheng's turnkey coating solution gives a tool maker full control of its own coating process, from incoming tools to inspected, coated product. The plant is built around the MD800 arc coater, with a fully automatic ultrasonic cleaning line, blasting equipment for target and liner maintenance, utilities and quality-control instruments. Owning the process keeps coating know-how in-house, allows your own coating recipes, and cuts turnaround to as little as the same day.",
      features:["Full control of your coating process and know-how","Open technology to develop your own coatings","Same-day coating turnaround possible","Universal process flow for many tool types"],
      specs:[["Cleaning","Fully automatic ultrasonic cleaning line, 14,000 pcs/h (APMT1135)"],["Coating","MD800 arc coater, 12,000 pcs per batch (APMT1135)"],["Target maintenance","9060A manual sandblaster, about 2 min per target"],["Liner maintenance","1212F pressurised sandblaster, about 4 h per set"],["Cooling","MCW-600 air-cooled chiller, 60 kW, R407C, 380 V 50 Hz"],["Pure water","CSJ-05 EDI water purifier, up to 18 MΩ·cm"],["Compressed air","SZ-30A permanent-magnet inverter compressor"],["Quality control","XHS-4700 ball crater tester, HR-150C Rockwell hardness tester, industrial microscope"]],
      process:["Cleaning","Coating","Target and liner maintenance","Inspection and dispatch"],url:"https://www.hscoat.com/turnkey-solution/",k:"turnkey plant job shop coating centre md800",i:["tools"]}
    ]}
  ]}
], null, 2));